#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir m2/repository                
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_40 ]
then
cd $OPENSHIFT_DATA_DIR
wget http://download.oracle.com/otn-pub/java/jdk/8u40-b26/jdk-8u40-linux-x64.tar.gz
tar xvf *.tar.gz
rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.1 ]
then
cd $OPENSHIFT_DATA_DIR
wget http://mirror.tcpdiag.net/apache/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.tar.gz
tar xvf *.tar.gz
rm -f *.tar.gz
fi

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_40
export MAVEN_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.3.1/
export MAVEN_OPTS="-Xms384m -Xmx412m"
export PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
java -version
mvn -version

cd $OPENSHIFT_REPO_DIR
mvn -s settings.xml clean package