#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir m2/repository                
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

export M2_HOME=$OPENSHIFT_DATA_DIR/apache-maven-3.2.3/
export MAVEN_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_40
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR
mvn -s settings.xml clean package